# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2cde69b2a19fc4f10229d33f0c56fce129969bcbae0205ee3fb1d96d85c4f73a11d19efea5e03177186a2fe063e4ce0d5637c671dbf73d19e29096e2f10cce1

test:
  secret_key_base: e85a2eaa5e705fab557dd0b25756759f2582220340ceba93e410f5dd82727580817364d108850af43ea81c90c73565b6ad21c11012907d936e690c409b69420e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
